[workspace]
members = [
     "frontend/exporter",
     "frontend/exporter/options",
     "frontend/diagnostics",
     "frontend/lint",
     "cli/options",
     "cli/options/engine",
     "cli/subcommands",
     "cli/driver",
     "test-harness",
]
exclude = ["tests"]

[workspace.dependencies]
itertools = "0.10.5"
schemars = "0.8"
which = "4.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
syn = { version = "1.0.107", features = [
     "derive",
     "printing",
     "extra-traits",
     "parsing",
     "full",
] }
adt-into = { path = "frontend/exporter/adt-into" }
log = "0.4"
pretty_env_logger = "0.4.0"
# Crates in this repository
circus-frontend-exporter = { path = "frontend/exporter" }
circus-cli-options = { path = "cli/options" }
circus-cli-options-engine = { path = "cli/options/engine" }
circus-frontend-exporter-options = { path = "frontend/exporter/options" }
circus-diagnostics = { path = "frontend/diagnostics" }
circus-lint = { version = "=0.1.0", path = "frontend/lint" }

