[package]
name = "riot-rs-runqueue"
version = "0.1.2"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2018"
description = "RIOT-rs runqueue implementation"
license = "Apache-2.0 / MIT"

[dependencies]
