[package]
name = "hax-lib"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme = "README.md"
description = "Hax-specific helpers for Rust programs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hax-lib-macros = { path = "../hax-lib-macros" }
num-bigint = "0.4.4"
num-traits = "0.2.18"
