[package]
name = "proverif-psk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hax-lib.workspace = true
libcrux = "=0.0.2-pre.2"

[dev-dependencies]
rand = { version = "0.8" }
