[package]
name = "hax-frontend-exporter"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
adt-into.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
itertools = "0.10.5"
hax-frontend-exporter-options.workspace = true
tracing.workspace = true
paste = "1.0.11"

[features]
default = ["minimal-ast"]
minimal-ast = []
