name: Release binaries for hax-engine

on:
  push:
    tags:
      - '*'

jobs:
  release-js:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: hacspec
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build JS
      run: nix build .#hax-engine.passthru.js -L -o hax-engine.js

    - run: |
        tar --dereference -czf hacspec_js.tar.gz hax-engine.js

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: hacspec_js.tar.gz

  release:
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest (See #4)
        ocaml-compiler: [4.14.x]
        
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - uses: dtolnay/rust-toolchain@1.70
          
      - run: cargo install --path cli/driver && cargo install --path cli/subcommands

      - run: opam install . --deps-only
        working-directory: engine
        
      - run: opam exec -- dune build
        working-directory: engine

      - run: |
          cp engine/_build/default/bin/native_driver.exe  hax-engine
          tar -czf hacspec_${{ matrix.os }}.tar.gz hax-engine
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: hacspec_${{ matrix.os }}.tar.gz

          
