[package]
name = "hax-diagnostics"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
serde.workspace = true
schemars.workspace = true
colored = "2"

